name: Deploy Next.js to Cloudflare Workers

on:
  push:
    branches: [ cloudflare ]   # deploy on new commits to branch 'cloudflare'
  workflow_dispatch:            # allow manual runs too

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      CLOUDFLARE_ACCOUNT_ID: a4b42b7ab379cbd7adf7d680ec724860
      CLOUDFLARE_API_TOKEN:  cgfz31CsaJNx4oDOHZtGleryj7Oj8Oer7S4bPqhq

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Build the Next.js app for Cloudflare Workers with OpenNext
      - name: Build (OpenNext)
        run: npx opennextjs-cloudflare build

      # Deploy the generated Worker + assets with Wrangler
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          # wrangler uses wrangler.toml at repo root (main=".open-next/worker.js")
          command: deploy
